create table tb_cliente
(
	co_cliente 			SERIAL PRIMARY KEY,
	no_cliente			varchar (100),
	ds_email			varchar(100),
	nu_telefone			varchar(20),
	ds_endereco         varchar(100),
	ds_cidade           varchar(100),
	ds_bairro           varchar(100),
	cd_uf               varchar(2),
	cd_cep	 			varchar(8)
);

create table tb_categoria
(
	co_categoria	SERIAL PRIMARY KEY,
	ds_categoria	varchar(100)
);

create table tb_produto
(
	co_produto 		SERIAL PRIMARY KEY,
	ds_produto		varchar(100),
	co_categoria	INTEGER,
	vl_preco		decimal(16,2),
	nu_quantidade	INTEGER,

CONSTRAINT fk_produto_categoria
    FOREIGN KEY (co_categoria)
    REFERENCES tb_categoria(co_categoria)
);

create table tb_status_pedido
(
	co_status 		SERIAL PRIMARY KEY,
	ds_status		varchar(100)
);

create table tb_pedido
(
	co_pedido 		SERIAL PRIMARY KEY,
	dt_pedido		DATE,
	co_cliente		INTEGER,
	co_status		INTEGER,

CONSTRAINT fk_pedido_cliente
    FOREIGN KEY (co_cliente)
    REFERENCES tb_cliente(co_cliente),

CONSTRAINT fk_pedido_status
    FOREIGN KEY (co_status)
    REFERENCES tb_status_pedido(co_status)

);

create table tb_pedido_item
(
	co_pedido_item	SERIAL PRIMARY KEY,
	co_pedido		INTEGER,
	co_produto		INTEGER,
	vl_preco		decimal(16,2),
	nu_quantidade	INTEGER,

CONSTRAINT fk_pedido_item
    FOREIGN KEY (co_pedido)
    REFERENCES tb_pedido(co_pedido),	

CONSTRAINT fk_pedido_item_produto
    FOREIGN KEY (co_produto)
    REFERENCES tb_produto(co_produto)	
);

insert into tb_categoria values (1, 'Camisetas');
insert into tb_categoria values (2, 'Camisas');
insert into tb_categoria values (3, 'Calças');
insert into tb_categoria values (4, 'Bermudas');
insert into tb_categoria values (5, 'Calções de banho');	
insert into tb_categoria values (6, 'Biquinis');		
insert into tb_categoria values (99, 'Outros');			

insert into tb_status_pedido values (1, 'Aguardando o pagamento');
insert into tb_status_pedido values (2, 'Pagamento confirmado');	
insert into tb_status_pedido values (3, 'Pagamento não autorizado');
insert into tb_status_pedido values (4, 'Separação dos produtos');
insert into tb_status_pedido values (5, 'Emissão de Nota Fiscal');
insert into tb_status_pedido values (6, 'Transportadora');
insert into tb_status_pedido values (7, 'Entregue');
insert into tb_status_pedido values (8, 'Devolução');	

insert into tb_cliente (co_cliente, no_cliente, ds_email) values (1, 'Alford Ofener', 'aofener0@blinklist.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (2, 'Emmerich Gaither', 'egaither1@theatlantic.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (3, 'Casar Connold', 'cconnold2@privacy.gov.au');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (4, 'Sharleen Branigan', 'sbranigan3@comcast.net');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (5, 'Renado Veldman', 'rveldman4@php.net');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (6, 'Saul Rebillard', 'srebillard5@google.co.jp');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (7, 'Nanon Keeley', 'nkeeley6@reference.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (8, 'Marketa Gillopp', 'mgillopp7@deviantart.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (9, 'Damian Beszant', 'dbeszant8@comcast.net');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (10, 'Ottilie Saddleton', 'osaddleton9@scribd.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (11, 'Bartholomeus Burgen', 'bburgena@mozilla.org');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (12, 'Jackquelin Withrington', 'jwithringtonb@soundcloud.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (13, 'Erny Lyfe', 'elyfec@go.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (14, 'Tabitha Sabathier', 'tsabathierd@si.edu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (15, 'Cobby Aspin', 'caspine@army.mil');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (16, 'Evelyn Espasa', 'eespasaf@mediafire.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (17, 'Vallie Schade', 'vschadeg@miitbeian.gov.cn');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (18, 'Elton Fawcus', 'efawcush@vk.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (19, 'Abbe Belcher', 'abelcheri@wp.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (20, 'Nettle Callaghan', 'ncallaghanj@bing.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (21, 'Jareb Kedge', 'jkedgek@ihg.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (22, 'Ermina Ferreri', 'eferreril@umn.edu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (23, 'Shelbi Moan', 'smoanm@kickstarter.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (24, 'Darice Roache', 'droachen@github.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (25, 'Allsun Place', 'aplaceo@dropbox.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (26, 'Liana Faircliff', 'lfaircliffp@uiuc.edu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (27, 'Hall Fuente', 'hfuenteq@xrea.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (28, 'Ripley Jewers', 'rjewersr@pagesperso-orange.fr');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (29, 'Elora Hazlehurst', 'ehazlehursts@aboutads.info');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (30, 'Patty Lingner', 'plingnert@ftc.gov');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (31, 'Reeta Sharvell', 'rsharvellu@cnet.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (32, 'Drucill Paffett', 'dpaffettv@businesswire.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (33, 'Mickey Misson', 'mmissonw@wiley.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (34, 'Cayla Sleford', 'cslefordx@gov.uk');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (35, 'Shane Danelutti', 'sdaneluttiy@linkedin.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (36, 'Ulrikaumeko Franschini', 'ufranschiniz@wikia.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (37, 'Leena Eyeington', 'leyeington10@independent.co.uk');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (38, 'Melodee Berrycloth', 'mberrycloth11@github.io');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (39, 'Lemar Caroli', 'lcaroli12@cnet.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (40, 'Idalina Goodacre', 'igoodacre13@google.es');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (41, 'Fred Ardern', 'fardern14@wiley.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (42, 'Gilberto Rodge', 'grodge15@github.io');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (43, 'Sinclare Stapele', 'sstapele16@google.es');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (44, 'Ashli Mendes', 'amendes17@salon.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (45, 'Murry Fulker', 'mfulker18@shareasale.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (46, 'Stacie Straffon', 'sstraffon19@zdnet.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (47, 'Moise Kingswoode', 'mkingswoode1a@imageshack.us');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (48, 'Kahlil Klees', 'kklees1b@360.cn');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (49, 'Tobiah Spurdens', 'tspurdens1c@statcounter.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (50, 'Jock Launder', 'jlaunder1d@wired.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (51, 'Clare Pentelow', 'cpentelow1e@webeden.co.uk');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (52, 'Wayland Gilyatt', 'wgilyatt1f@sogou.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (53, 'Mercy Petrasch', 'mpetrasch1g@home.pl');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (54, 'Theodora Bellham', 'tbellham1h@i2i.jp');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (55, 'Harley Ciobotaru', 'hciobotaru1i@weebly.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (56, 'Marney McClinton', 'mmcclinton1j@twitter.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (57, 'Borg Bage', 'bbage1k@prweb.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (58, 'Lek Probbings', 'lprobbings1l@ameblo.jp');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (59, 'Mikel Capelin', 'mcapelin1m@amazon.de');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (60, 'Olympie Offiler', 'ooffiler1n@indiatimes.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (61, 'Roanna Kryzhov', 'rkryzhov1o@admin.ch');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (62, 'Laurel Wanka', 'lwanka1p@yelp.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (63, 'Leoline Woolfall', 'lwoolfall1q@cmu.edu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (64, 'Amelita Raff', 'araff1r@moonfruit.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (65, 'Ree Sharple', 'rsharple1s@springer.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (66, 'Rhodie Spring', 'rspring1t@fotki.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (67, 'Arnuad Kivlin', 'akivlin1u@diigo.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (68, 'Gertrude Bartlett', 'gbartlett1v@census.gov');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (69, 'Una Kloisner', 'ukloisner1w@t-online.de');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (70, 'Lovell Abbado', 'labbado1x@homestead.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (71, 'Kleon Vedenichev', 'kvedenichev1y@mediafire.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (72, 'Frazer Fishburn', 'ffishburn1z@scribd.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (73, 'Hillier Devo', 'hdevo20@amazon.de');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (74, 'Theda Gemelli', 'tgemelli21@163.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (75, 'Gunilla Waddoups', 'gwaddoups22@jigsy.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (76, 'Stacee Dowsey', 'sdowsey23@reference.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (77, 'Esmaria Fright', 'efright24@livejournal.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (78, 'Brenn Pott', 'bpott25@tamu.edu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (79, 'Rowland Woolforde', 'rwoolforde26@godaddy.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (80, 'Raffaello Burgan', 'rburgan27@amazon.de');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (81, 'Harald Broadwood', 'hbroadwood28@gravatar.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (82, 'Damiano Mayston', 'dmayston29@e-recht24.de');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (83, 'Marnie Pabst', 'mpabst2a@accuweather.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (84, 'Livia McVitty', 'lmcvitty2b@kickstarter.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (85, 'Charleen Hanne', 'channe2c@comcast.net');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (86, 'Victor Goggen', 'vgoggen2d@simplemachines.org');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (87, 'Gasparo Scowcroft', 'gscowcroft2e@wp.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (88, 'Banky Cuthbertson', 'bcuthbertson2f@smugmug.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (89, 'Sig Sitwell', 'ssitwell2g@goo.gl');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (90, 'Walsh Simyson', 'wsimyson2h@goo.gl');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (91, 'Waverley Overel', 'woverel2i@slashdot.org');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (92, 'Hubert Petranek', 'hpetranek2j@cbslocal.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (93, 'Asa Pegram', 'apegram2k@bandcamp.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (94, 'Barthel Blood', 'bblood2l@phoca.cz');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (95, 'Scot Heffernan', 'sheffernan2m@intel.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (96, 'Giffer Sallows', 'gsallows2n@about.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (97, 'Chlo Sporner', 'csporner2o@cpanel.net');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (98, 'Gelya Alty', 'galty2p@thetimes.co.uk');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (99, 'Link Diggles', 'ldiggles2q@macromedia.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (100, 'Gerda Huckfield', 'ghuckfield2r@reddit.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (101, 'Miguel Cobbing', 'mcobbing2s@dion.ne.jp');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (102, 'Jeddy Dibnah', 'jdibnah2t@free.fr');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (103, 'Sargent Jiruch', 'sjiruch2u@youtube.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (104, 'Libbey Albisser', 'lalbisser2v@cam.ac.uk');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (105, 'Leonanie Banbrook', 'lbanbrook2w@naver.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (106, 'Marcy McOwan', 'mmcowan2x@bloglovin.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (107, 'Brandi Hambling', 'bhambling2y@latimes.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (108, 'Stephana Ingrem', 'singrem2z@virginia.edu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (109, 'Luigi Spracklin', 'lspracklin30@github.io');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (110, 'Ban Kerrod', 'bkerrod31@prweb.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (111, 'Tobin Renzo', 'trenzo32@rambler.ru');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (112, 'Joachim Tolley', 'jtolley33@utexas.edu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (113, 'Evelina Gascoigne', 'egascoigne34@privacy.gov.au');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (114, 'Lenora Walas', 'lwalas35@com.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (115, 'Dacie Conrad', 'dconrad36@vistaprint.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (116, 'Collie Threlkeld', 'cthrelkeld37@xrea.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (117, 'Audie Sieur', 'asieur38@alibaba.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (118, 'Felice Barcke', 'fbarcke39@abc.net.au');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (119, 'Rebbecca Faull', 'rfaull3a@google.pl');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (120, 'Nat Greally', 'ngreally3b@arstechnica.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (121, 'Winnie Brittan', 'wbrittan3c@parallels.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (122, 'Ddene Atty', 'datty3d@soundcloud.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (123, 'Myrta Cammocke', 'mcammocke3e@sun.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (124, 'Hashim Coper', 'hcoper3f@cafepress.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (125, 'Miran Foggo', 'mfoggo3g@independent.co.uk');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (126, 'Tarah Yes', 'tyes3h@mayoclinic.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (127, 'Keelby Danielovitch', 'kdanielovitch3i@webeden.co.uk');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (128, 'Alicea Janota', 'ajanota3j@freewebs.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (129, 'Lusa Ketts', 'lketts3k@taobao.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (130, 'Templeton Flaxman', 'tflaxman3l@webmd.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (131, 'Tudor Castaner', 'tcastaner3m@friendfeed.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (132, 'Katuscha Pawlata', 'kpawlata3n@seattletimes.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (133, 'Rossie Brands', 'rbrands3o@cmu.edu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (134, 'Anni Espasa', 'aespasa3p@bluehost.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (135, 'Armstrong Lemmen', 'alemmen3q@jigsy.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (136, 'Katti Pretorius', 'kpretorius3r@cornell.edu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (137, 'Evy Deex', 'edeex3s@wiley.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (138, 'Konstantine Surplice', 'ksurplice3t@washingtonpost.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (139, 'Steve Linklet', 'slinklet3u@oaic.gov.au');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (140, 'Daile Tilzey', 'dtilzey3v@admin.ch');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (141, 'Derwin Bagster', 'dbagster3w@yandex.ru');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (142, 'Ancell Ghost', 'aghost3x@goo.ne.jp');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (143, 'Felisha Ravillas', 'fravillas3y@woothemes.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (144, 'Ludovico McGeachey', 'lmcgeachey3z@gravatar.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (145, 'Merwin Northcott', 'mnorthcott40@uol.com.br');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (146, 'Vincenty Mewburn', 'vmewburn41@sun.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (147, 'Iorgos Tredinnick', 'itredinnick42@house.gov');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (148, 'Willetta Almak', 'walmak43@google.ru');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (149, 'Mauricio Punyer', 'mpunyer44@1688.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (150, 'Gelya Becket', 'gbecket45@myspace.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (151, 'Zachary Coe', 'zcoe46@altervista.org');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (152, 'Greer Beverstock', 'gbeverstock47@businessinsider.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (153, 'Orly Snodin', 'osnodin48@is.gd');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (154, 'Gearalt Bransgrove', 'gbransgrove49@canalblog.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (155, 'Annis Shillaber', 'ashillaber4a@sciencedaily.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (156, 'Renelle Bohills', 'rbohills4b@vk.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (157, 'Bevvy Sparwell', 'bsparwell4c@go.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (158, 'Althea Perillo', 'aperillo4d@omniture.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (159, 'Brannon Truckell', 'btruckell4e@tumblr.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (160, 'Matthiew Raincin', 'mraincin4f@usda.gov');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (161, 'Ezequiel Hollier', 'ehollier4g@google.com.hk');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (162, 'Dick Moogan', 'dmoogan4h@nydailynews.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (163, 'Aurilia Drinnan', 'adrinnan4i@live.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (164, 'Serge McConnulty', 'smcconnulty4j@arstechnica.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (165, 'Dani Tregent', 'dtregent4k@paypal.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (166, 'Chad Kedslie', 'ckedslie4l@usatoday.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (167, 'Joanna Muston', 'jmuston4m@ow.ly');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (168, 'Abeu Ziemke', 'aziemke4n@com.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (169, 'Ibby McGaugie', 'imcgaugie4o@cbslocal.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (170, 'Tarrance Laydon', 'tlaydon4p@vimeo.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (171, 'Francis Heyburn', 'fheyburn4q@opera.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (172, 'Claudian Chasmer', 'cchasmer4r@un.org');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (173, 'Ikey Warrillow', 'iwarrillow4s@theguardian.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (174, 'Verla Razzell', 'vrazzell4t@over-blog.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (175, 'Dennet Benedtti', 'dbenedtti4u@reddit.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (176, 'Ofilia Falla', 'ofalla4v@blogs.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (177, 'Mathew Minchenton', 'mminchenton4w@marketwatch.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (178, 'Lani Dimitriou', 'ldimitriou4x@cbslocal.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (179, 'Lizette Lepard', 'llepard4y@mysql.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (180, 'Terrill Munkton', 'tmunkton4z@tiny.cc');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (181, 'Celina Pantry', 'cpantry50@noaa.gov');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (182, 'Loraine Aggio', 'laggio51@hp.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (183, 'Cairistiona Cockshot', 'ccockshot52@upenn.edu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (184, 'Douglass Beveridge', 'dbeveridge53@surveymonkey.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (185, 'Millard Polino', 'mpolino54@berkeley.edu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (186, 'Reynolds Guillotin', 'rguillotin55@yellowpages.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (187, 'Berkley Buscher', 'bbuscher56@hao123.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (188, 'Zoe Pele', 'zpele57@1688.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (189, 'Ara McKendo', 'amckendo58@europa.eu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (190, 'Agnese Wearn', 'awearn59@naver.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (191, 'Kirk Penniall', 'kpenniall5a@tinyurl.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (192, 'Willie Shervil', 'wshervil5b@diigo.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (193, 'Farly Halward', 'fhalward5c@theatlantic.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (194, 'Gabi Boatwright', 'gboatwright5d@ehow.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (195, 'Xymenes Welds', 'xwelds5e@blogs.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (196, 'Curr Winters', 'cwinters5f@digg.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (197, 'Goddart Ciobotaru', 'gciobotaru5g@businessweek.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (198, 'Killian Burkwood', 'kburkwood5h@time.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (199, 'Berenice Faulkes', 'bfaulkes5i@wikia.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (200, 'Saudra Leonards', 'sleonards5j@yelp.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (201, 'Zora Leil', 'zleil5k@nbcnews.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (202, 'Zitella De Avenell', 'zdeavenell5l@abc.net.au');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (203, 'Zacherie Corder', 'zcorder5m@businesswire.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (204, 'Jordan Ronaldson', 'jronaldson5n@google.com.au');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (205, 'Flinn Podd', 'fpodd5o@dropbox.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (206, 'Giana Rigate', 'grigate5p@washingtonpost.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (207, 'Zeb Berard', 'zberard5q@sphinn.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (208, 'Bettina Jakubowski', 'bjakubowski5r@nymag.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (209, 'Eleanora Woofenden', 'ewoofenden5s@hibu.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (210, 'Briano Bater', 'bbater5t@indiegogo.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (211, 'Baldwin Huggons', 'bhuggons5u@hud.gov');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (212, 'Husein Cornbell', 'hcornbell5v@nymag.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (213, 'Kynthia Cantero', 'kcantero5w@wix.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (214, 'Goraud Pepper', 'gpepper5x@cbslocal.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (215, 'Ann Brozek', 'abrozek5y@storify.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (216, 'Maude Baggott', 'mbaggott5z@purevolume.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (217, 'Loree Crevagh', 'lcrevagh60@buzzfeed.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (218, 'Herby Schooling', 'hschooling61@g.co');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (219, 'Benn Adie', 'badie62@desdev.cn');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (220, 'Martica Grichukhin', 'mgrichukhin63@g.co');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (221, 'Whitby Wastie', 'wwastie64@hud.gov');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (222, 'Tremayne Girdlestone', 'tgirdlestone65@t-online.de');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (223, 'Tracie Gronowe', 'tgronowe66@europa.eu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (224, 'Jerrie Hodgin', 'jhodgin67@myspace.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (225, 'Elfreda Wordsworth', 'ewordsworth68@admin.ch');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (226, 'Stormi Mattek', 'smattek69@xrea.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (227, 'Saw Geerdts', 'sgeerdts6a@hp.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (228, 'Deeanne de Quesne', 'ddequesne6b@hugedomains.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (229, 'Munroe Becke', 'mbecke6c@bbb.org');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (230, 'Cecil Foldes', 'cfoldes6d@ycombinator.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (231, 'Wiatt Lavis', 'wlavis6e@yolasite.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (232, 'Willard Helliker', 'whelliker6f@chron.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (233, 'Karlotte Morgans', 'kmorgans6g@blinklist.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (234, 'Bronson Parvin', 'bparvin6h@canalblog.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (235, 'Rockwell Lindeman', 'rlindeman6i@linkedin.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (236, 'Aurelia Winslade', 'awinslade6j@wikimedia.org');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (237, 'Agnola Scotter', 'ascotter6k@gizmodo.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (238, 'Margo Lace', 'mlace6l@fotki.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (239, 'Talya Learmonth', 'tlearmonth6m@google.cn');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (240, 'Rory Gennerich', 'rgennerich6n@guardian.co.uk');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (241, 'Irvine Elnough', 'ielnough6o@uiuc.edu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (242, 'Say Myderscough', 'smyderscough6p@youku.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (243, 'Bradford Jeanequin', 'bjeanequin6q@vimeo.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (244, 'Gifford Philipot', 'gphilipot6r@imgur.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (245, 'Nikolai Sixsmith', 'nsixsmith6s@icq.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (246, 'Tani Jain', 'tjain6t@webnode.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (247, 'Elora Marquese', 'emarquese6u@gnu.org');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (248, 'Kassia Manger', 'kmanger6v@de.vu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (249, 'Nestor McHugh', 'nmchugh6w@senate.gov');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (250, 'Vassili Dealey', 'vdealey6x@behance.net');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (251, 'Gerald Jessep', 'gjessep6y@webmd.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (252, 'Lincoln Cruikshank', 'lcruikshank6z@slideshare.net');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (253, 'Darin Kobpac', 'dkobpac70@alibaba.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (254, 'Thorstein Kenrat', 'tkenrat71@google.ca');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (255, 'Daisi Sutherland', 'dsutherland72@time.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (256, 'Arty Reeks', 'areeks73@soup.io');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (257, 'Prudence Tute', 'ptute74@com.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (258, 'Giacopo MacKomb', 'gmackomb75@examiner.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (259, 'Jim Felton', 'jfelton76@etsy.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (260, 'Thomasa Placstone', 'tplacstone77@phpbb.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (261, 'Welch Casillas', 'wcasillas78@ebay.co.uk');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (262, 'August Dalyiel', 'adalyiel79@ucoz.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (263, 'Natasha Pagel', 'npagel7a@goo.ne.jp');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (264, 'Vinny Trevon', 'vtrevon7b@house.gov');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (265, 'Randal Stripling', 'rstripling7c@unc.edu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (266, 'Allistir Chaplyn', 'achaplyn7d@surveymonkey.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (267, 'Aubine Oluwatoyin', 'aoluwatoyin7e@a8.net');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (268, 'Serge Chasemoore', 'schasemoore7f@about.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (269, 'Eada Fontaine', 'efontaine7g@aboutads.info');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (270, 'Whittaker Bartolomeu', 'wbartolomeu7h@go.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (271, 'Maible Tinner', 'mtinner7i@harvard.edu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (272, 'Cole Mattin', 'cmattin7j@sciencedirect.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (273, 'Urbain Facey', 'ufacey7k@epa.gov');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (274, 'Breena Orridge', 'borridge7l@independent.co.uk');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (275, 'Valentia Thompson', 'vthompson7m@techcrunch.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (276, 'Seumas Boraston', 'sboraston7n@tripod.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (277, 'Maxwell Skillett', 'mskillett7o@noaa.gov');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (278, 'Clemente Mortlock', 'cmortlock7p@home.pl');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (279, 'Fawnia Swiffen', 'fswiffen7q@apple.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (280, 'Dov Magnus', 'dmagnus7r@oracle.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (281, 'Nicolis Burnyate', 'nburnyate7s@java.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (282, 'Essie Skill', 'eskill7t@icio.us');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (283, 'Kelsi McLuckie', 'kmcluckie7u@nps.gov');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (284, 'Alistair Blankau', 'ablankau7v@mashable.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (285, 'Olympie Gallagher', 'ogallagher7w@mlb.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (286, 'Worth Arnot', 'warnot7x@elegantthemes.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (287, 'Obediah Bourdas', 'obourdas7y@ifeng.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (288, 'Daphene Gopsell', 'dgopsell7z@tinypic.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (289, 'Linnea Sekulla', 'lsekulla80@nhs.uk');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (290, 'Darcy Stithe', 'dstithe81@npr.org');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (291, 'Calley Ineson', 'cineson82@amazon.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (292, 'Lawrence Voyce', 'lvoyce83@mit.edu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (293, 'Ezechiel Geraldini', 'egeraldini84@webs.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (294, 'Berkeley Sweett', 'bsweett85@washingtonpost.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (295, 'Darius Yelding', 'dyelding86@nifty.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (296, 'Clyde Lambell', 'clambell87@nydailynews.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (297, 'Anjanette Derisly', 'aderisly88@globo.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (298, 'Brady Zannuto', 'bzannuto89@bigcartel.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (299, 'Mickey Chapier', 'mchapier8a@livejournal.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (300, 'Reinaldo McCoole', 'rmccoole8b@cyberchimps.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (301, 'Erinna Jahnisch', 'ejahnisch8c@usatoday.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (302, 'Kym Wadley', 'kwadley8d@tripod.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (303, 'Hastie Quarlis', 'hquarlis8e@msu.edu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (304, 'Egor Thynn', 'ethynn8f@ning.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (305, 'Dasha Landre', 'dlandre8g@cdc.gov');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (306, 'Allister Arrigucci', 'aarrigucci8h@loc.gov');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (307, 'Gerardo Alelsandrovich', 'galelsandrovich8i@webmd.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (308, 'Mickie Boole', 'mboole8j@yellowbook.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (309, 'Merola Rouchy', 'mrouchy8k@ucla.edu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (310, 'Ricca Schellig', 'rschellig8l@usa.gov');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (311, 'Galven Ladewig', 'gladewig8m@sina.com.cn');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (312, 'Kinnie Southam', 'ksoutham8n@parallels.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (313, 'Felice Crighton', 'fcrighton8o@amazon.co.uk');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (314, 'Monro McGorman', 'mmcgorman8p@shareasale.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (315, 'Hannie Mattiussi', 'hmattiussi8q@alibaba.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (316, 'Benedick Gaythorpe', 'bgaythorpe8r@taobao.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (317, 'Dorita Herion', 'dherion8s@instagram.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (318, 'Joann Gladdin', 'jgladdin8t@free.fr');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (319, 'Deana Petre', 'dpetre8u@quantcast.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (320, 'Bryant Pollicote', 'bpollicote8v@cam.ac.uk');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (321, 'Bette Criag', 'bcriag8w@domainmarket.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (322, 'Victoir Gehricke', 'vgehricke8x@squarespace.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (323, 'Mikaela Puddin', 'mpuddin8y@salon.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (324, 'Emilee Kettle', 'ekettle8z@epa.gov');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (325, 'Rad Juanes', 'rjuanes90@gnu.org');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (326, 'Towney Elfitt', 'telfitt91@wp.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (327, 'Rance Brodnecke', 'rbrodnecke92@irs.gov');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (328, 'Bancroft Alfonsetto', 'balfonsetto93@umn.edu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (329, 'Fons Redgewell', 'fredgewell94@state.tx.us');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (330, 'Rand Dubois', 'rdubois95@pen.io');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (331, 'Wynn Twelftree', 'wtwelftree96@elpais.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (332, 'Diannne Sansom', 'dsansom97@facebook.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (333, 'Margaretta Grigoroni', 'mgrigoroni98@last.fm');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (334, 'Wrennie Souter', 'wsouter99@bbb.org');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (335, 'Corenda Chance', 'cchance9a@springer.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (336, 'Gifford Langabeer', 'glangabeer9b@auda.org.au');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (337, 'Evey Fransemai', 'efransemai9c@blinklist.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (338, 'Lizette Hymas', 'lhymas9d@free.fr');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (339, 'Liane Child', 'lchild9e@alibaba.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (340, 'Esme Gland', 'egland9f@cyberchimps.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (341, 'Gabriello Manktelow', 'gmanktelow9g@ow.ly');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (342, 'Ellerey Geddes', 'egeddes9h@usatoday.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (343, 'Laverne Farlam', 'lfarlam9i@privacy.gov.au');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (344, 'Rochester Ledes', 'rledes9j@woothemes.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (345, 'Pepi Plumm', 'pplumm9k@facebook.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (346, 'Robinson Candelin', 'rcandelin9l@howstuffworks.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (347, 'Homer Guys', 'hguys9m@forbes.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (348, 'Olenka Philippet', 'ophilippet9n@trellian.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (349, 'Marcy Eltun', 'meltun9o@ameblo.jp');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (350, 'Taryn Howchin', 'thowchin9p@biblegateway.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (351, 'Sheffy Gaunter', 'sgaunter9q@edublogs.org');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (352, 'Tabor Oakhill', 'toakhill9r@unicef.org');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (353, 'Gunar Beneyto', 'gbeneyto9s@springer.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (354, 'Guilbert Callar', 'gcallar9t@csmonitor.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (355, 'Mike Dyshart', 'mdyshart9u@google.cn');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (356, 'Nicolis Brevetor', 'nbrevetor9v@comcast.net');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (357, 'Umberto Kewzick', 'ukewzick9w@plala.or.jp');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (358, 'Corenda Polding', 'cpolding9x@mac.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (359, 'Chas Esslemont', 'cesslemont9y@china.com.cn');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (361, 'Ermin Rogez', 'erogeza0@xing.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (362, 'Margi Hinkins', 'mhinkinsa1@dmoz.org');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (363, 'Ban Abramzon', 'babramzona2@unicef.org');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (364, 'Nara Dahill', 'ndahilla3@house.gov');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (365, 'Patrizia Smidmoor', 'psmidmoora4@google.ca');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (366, 'Martita Tordoff', 'mtordoffa5@walmart.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (367, 'Auguste Kliche', 'aklichea6@tamu.edu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (368, 'Ottilie Dallas', 'odallasa7@about.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (369, 'Siusan Cockin', 'scockina8@rakuten.co.jp');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (370, 'Patrizius Bastard', 'pbastarda9@microsoft.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (371, 'Monty Brayshay', 'mbrayshayaa@ifeng.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (372, 'Skelly Houndesome', 'shoundesomeab@shutterfly.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (373, 'Nonna Matousek', 'nmatousekac@bizjournals.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (374, 'Erich Grover', 'egroverad@163.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (375, 'Gun Cowburn', 'gcowburnae@twitter.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (376, 'Trudie Cluely', 'tcluelyaf@biblegateway.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (377, 'Keane Tait', 'ktaitag@tripod.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (378, 'Mirabelle Ragdale', 'mragdaleah@sfgate.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (379, 'Ulrick Shenfish', 'ushenfishai@dedecms.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (380, 'Franklin Bestwick', 'fbestwickaj@hhs.gov');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (381, 'Nicole Cashley', 'ncashleyak@japanpost.jp');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (382, 'Jarrad Millhouse', 'jmillhouseal@cmu.edu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (383, 'Hazel Braghini', 'hbraghiniam@dropbox.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (384, 'Vernen Barkhouse', 'vbarkhousean@go.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (385, 'Maura Scala', 'mscalaao@ibm.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (386, 'Johnna Teece', 'jteeceap@accuweather.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (387, 'Pauly Meni', 'pmeniaq@cyberchimps.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (388, 'Allina De Marchi', 'ademarchiar@ameblo.jp');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (389, 'Duky Levens', 'dlevensas@ihg.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (390, 'Lanae Bantham', 'lbanthamat@networksolutions.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (391, 'Laurena Fullicks', 'lfullicksau@nytimes.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (392, 'Borg Elderbrant', 'belderbrantav@privacy.gov.au');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (393, 'Willem Sankey', 'wsankeyaw@auda.org.au');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (394, 'Maggi Maltster', 'mmaltsterax@hatena.ne.jp');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (395, 'Francklin Sheriff', 'fsheriffay@telegraph.co.uk');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (396, 'Roda Keesman', 'rkeesmanaz@nasa.gov');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (397, 'Latashia Spragg', 'lspraggb0@jigsy.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (398, 'Sanderson Figin', 'sfiginb1@comsenz.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (399, 'Pris Pietersen', 'ppietersenb2@myspace.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (400, 'Wayland Scullion', 'wscullionb3@oaic.gov.au');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (401, 'Sheela Endrighi', 'sendrighib4@ning.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (402, 'Munroe Golborn', 'mgolbornb5@studiopress.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (403, 'Pru Dumbrill', 'pdumbrillb6@wikia.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (404, 'Audry Fewtrell', 'afewtrellb7@cbsnews.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (405, 'Duff Le Prevost', 'dleprevostb8@independent.co.uk');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (406, 'Hadria Hallworth', 'hhallworthb9@bbc.co.uk');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (407, 'Keene Druhan', 'kdruhanba@google.co.jp');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (408, 'Bradford Ondrusek', 'bondrusekbb@wikipedia.org');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (409, 'Brynn Bruckmann', 'bbruckmannbc@xrea.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (410, 'Yetta Temprell', 'ytemprellbd@globo.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (411, 'Othilia Trouncer', 'otrouncerbe@fda.gov');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (412, 'Basil Meneghi', 'bmeneghibf@addtoany.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (413, 'Herby Verling', 'hverlingbg@yellowbook.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (414, 'Joy Mixture', 'jmixturebh@printfriendly.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (415, 'Paquito Flatt', 'pflattbi@wp.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (416, 'Portie Gooda', 'pgoodabj@istockphoto.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (417, 'Brigida Jaggs', 'bjaggsbk@yelp.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (418, 'Morse Caunce', 'mcauncebl@soundcloud.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (419, 'Yard McGivena', 'ymcgivenabm@surveymonkey.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (420, 'Fidelity Whalley', 'fwhalleybn@freewebs.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (421, 'Rouvin Kimmings', 'rkimmingsbo@pagesperso-orange.fr');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (422, 'Mendie Haydock', 'mhaydockbp@un.org');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (423, 'Cristiano Rangall', 'crangallbq@unblog.fr');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (424, 'Enid Farherty', 'efarhertybr@sphinn.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (425, 'Raff Matterdace', 'rmatterdacebs@vk.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (426, 'Dotti Dumbar', 'ddumbarbt@360.cn');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (427, 'Francklin Crank', 'fcrankbu@ihg.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (428, 'Melli Motion', 'mmotionbv@cnet.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (430, 'Aurilia Murney', 'amurneybx@usnews.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (431, 'Carolee Lucia', 'cluciaby@acquirethisname.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (432, 'Mario Shingles', 'mshinglesbz@salon.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (433, 'Patrizia Housby', 'phousbyc0@woothemes.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (434, 'Salomi Glasebrook', 'sglasebrookc1@sakura.ne.jp');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (435, 'Brittne Minor', 'bminorc2@upenn.edu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (436, 'Solly McWhinnie', 'smcwhinniec3@ameblo.jp');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (437, 'Darin Poundford', 'dpoundfordc4@smh.com.au');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (438, 'Juana Harkness', 'jharknessc5@uiuc.edu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (439, 'Trescha Mettrick', 'tmettrickc6@wikia.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (440, 'Far Crisell', 'fcrisellc7@go.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (441, 'Yuma De Courtney', 'ydecourtneyc8@cisco.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (442, 'Yard Duberry', 'yduberryc9@dagondesign.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (443, 'Etienne Voden', 'evodenca@merriam-webster.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (444, 'Karrah Dalby', 'kdalbycb@disqus.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (445, 'Dinnie Cape', 'dcapecc@behance.net');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (446, 'Jereme Mulford', 'jmulfordcd@nhs.uk');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (447, 'Liuka Pinnell', 'lpinnellce@oaic.gov.au');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (448, 'Bethanne Moylan', 'bmoylancf@cmu.edu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (449, 'Dana Meller', 'dmellercg@google.co.jp');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (450, 'Amos Kenner', 'akennerch@deviantart.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (451, 'Tommi Salmond', 'tsalmondci@google.com.br');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (452, 'Maximilian Danko', 'mdankocj@paypal.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (453, 'Deane Foat', 'dfoatck@canalblog.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (454, 'Carrissa Gianuzzi', 'cgianuzzicl@rediff.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (455, 'Gratia Buttress', 'gbuttresscm@squidoo.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (456, 'Alexandro Pattullo', 'apattullocn@flavors.me');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (457, 'Saidee Delouch', 'sdelouchco@cpanel.net');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (458, 'Codie Altamirano', 'caltamiranocp@fda.gov');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (459, 'Claybourne Hambatch', 'chambatchcq@4shared.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (460, 'Isaiah Aksell', 'iaksellcr@kickstarter.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (461, 'Leyla Landsman', 'llandsmancs@reuters.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (462, 'Yorke Davsley', 'ydavsleyct@hud.gov');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (463, 'Nicko Guerrier', 'nguerriercu@wordpress.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (464, 'Beckie Berrick', 'bberrickcv@arstechnica.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (465, 'Camel Chittleburgh', 'cchittleburghcw@histats.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (466, 'Celia Domenico', 'cdomenicocx@over-blog.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (467, 'Maurizia Megarrell', 'mmegarrellcy@businessinsider.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (468, 'Chaddy Meakes', 'cmeakescz@pbs.org');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (469, 'Kristian Gaven', 'kgavend0@eventbrite.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (470, 'Alisa Wrightson', 'awrightsond1@skype.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (471, 'Roth MacAughtrie', 'rmacaughtried2@domainmarket.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (472, 'Darby Ramsdale', 'dramsdaled3@yandex.ru');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (473, 'Hope Drache', 'hdrached4@ask.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (474, 'Joanne Loy', 'jloyd5@exblog.jp');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (475, 'Anet Dyball', 'adyballd6@reuters.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (476, 'Shara Crossdale', 'scrossdaled7@businessinsider.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (478, 'Yetty Esel', 'yeseld9@kickstarter.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (479, 'Tamra Phizaclea', 'tphizacleada@si.edu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (480, 'Chen Costellow', 'ccostellowdb@umn.edu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (481, 'Ed Corsham', 'ecorshamdc@apache.org');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (482, 'Granger Martinovsky', 'gmartinovskydd@kickstarter.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (483, 'Ignace Tuftin', 'ituftinde@reddit.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (484, 'Danya Boddington', 'dboddingtondf@sciencedirect.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (485, 'Neale Colleran', 'ncollerandg@cnn.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (486, 'Alvy Spurret', 'aspurretdh@apple.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (487, 'Melantha Edlyn', 'medlyndi@php.net');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (488, 'Arlene Rubery', 'aruberydj@pagesperso-orange.fr');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (489, 'Gates Cleave', 'gcleavedk@nature.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (490, 'Marshal Myderscough', 'mmyderscoughdl@rambler.ru');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (491, 'Harmonia Salvin', 'hsalvindm@jimdo.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (492, 'Christan Ryder', 'cryderdn@microsoft.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (493, 'Juli Linstead', 'jlinsteaddo@free.fr');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (494, 'Selig Gaffon', 'sgaffondp@biglobe.ne.jp');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (495, 'Ferne Human', 'fhumandq@domainmarket.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (496, 'Stanfield Thorn', 'sthorndr@ca.gov');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (497, 'Zelma Candey', 'zcandeyds@ucoz.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (498, 'Hasty Bonder', 'hbonderdt@cbsnews.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (499, 'Fina Earngy', 'fearngydu@studiopress.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (500, 'Berkeley Vasilik', 'bvasilikdv@alibaba.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (501, 'Juliana Plewman', 'jplewmandw@usgs.gov');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (502, 'Jerrie Isard', 'jisarddx@gizmodo.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (503, 'Gloriane Roch', 'grochdy@ft.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (504, 'Chiquita Janssens', 'cjanssensdz@marriott.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (505, 'Lainey Bonsey', 'lbonseye0@usatoday.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (506, 'Khalil Windeatt', 'kwindeatte1@statcounter.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (507, 'Gabi Eacle', 'geaclee2@wordpress.org');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (508, 'Angeline Abendroth', 'aabendrothe3@cdc.gov');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (509, 'Theodor Everit', 'teverite4@ucoz.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (510, 'Jewell Hawkwood', 'jhawkwoode5@elegantthemes.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (511, 'Sigismundo Brocklesby', 'sbrocklesbye6@dion.ne.jp');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (512, 'Ethan Fullagar', 'efullagare7@wiley.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (513, 'Cal Herche', 'cherchee8@themeforest.net');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (514, 'Skipper Whiff', 'swhiffe9@columbia.edu');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (515, 'Adham Cossons', 'acossonsea@sitemeter.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (516, 'Janella Syddie', 'jsyddieeb@vkontakte.ru');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (517, 'Otis Oake', 'ooakeec@newyorker.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (518, 'Merline Spinke', 'mspinkeed@webmd.com');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (519, 'Manfred Morrison', 'mmorrisonee@jugem.jp');
insert into tb_cliente (co_cliente, no_cliente, ds_email) values (520, 'Broderic Alejandre', 'balejandreef@gnu.org');

insert into tb_produto (co_produto, co_categoria, vl_preco, nu_quantidade, ds_produto) values (1, 99, 100, 20, 'SHORT SURF SLIM FIT ESTAMPADO DOTS PRETO');
insert into tb_produto (co_produto, co_categoria, vl_preco, nu_quantidade, ds_produto) values (2, 99, 100, 20, 'SHORT SURF SLIM FIT ESTAMPADO ONCA BLUE AZUL');	
insert into tb_produto (co_produto, co_categoria, vl_preco, nu_quantidade, ds_produto) values (3, 99, 100, 20, 'SHORT SURF PREMIUM LISTRA PB PRETO');
insert into tb_produto (co_produto, co_categoria, vl_preco, nu_quantidade, ds_produto) values (4, 99, 100, 20, 'BERMUDA MOLETOM CLASSICA COLORS CINZA');
insert into tb_produto (co_produto, co_categoria, vl_preco, nu_quantidade, ds_produto) values (5, 99, 85, 30, 'T-SHIRT TINTURADA SILK 85 VERMELHO');
insert into tb_produto (co_produto, co_categoria, vl_preco, nu_quantidade, ds_produto) values (6, 99, 85, 30, 'T SHIRT SILK FRIES BRANCO');
insert into tb_produto (co_produto, co_categoria, vl_preco, nu_quantidade, ds_produto) values (7, 99, 85, 30, 'T SHIRT MANGA LONGA LOGO PRETO');
insert into tb_produto (co_produto, co_categoria, vl_preco, nu_quantidade, ds_produto) values (8, 99, 85, 30, 'T SHIRT SILK LOCALS BRANCO');
insert into tb_produto (co_produto, co_categoria, vl_preco, nu_quantidade, ds_produto) values (9, 99, 85, 30, 'T SHIRT SILK WALK THIS WAY 77M PRETO');
insert into tb_produto (co_produto, co_categoria, vl_preco, nu_quantidade, ds_produto) values (10, 99, 85, 30, 'T-SHIRT TINTURADA POWER LIGHT PRETO');
insert into tb_produto (co_produto, co_categoria, vl_preco, nu_quantidade, ds_produto) values (11, 99, 85, 30, 'T SHIRT TINTURADA POSTER VINTAGE AZUL CLARO');
insert into tb_produto (co_produto, co_categoria, vl_preco, nu_quantidade, ds_produto) values (12, 99, 145, 45, 'CALÇA CONFORT SARJA BLACK PRETO');
insert into tb_produto (co_produto, co_categoria, vl_preco, nu_quantidade, ds_produto) values (13, 99, 145, 45, 'CALÇA CONFORT SARJA BRANCO');
insert into tb_produto (co_produto, co_categoria, vl_preco, nu_quantidade, ds_produto) values (14, 99, 145, 45, 'CALÇA JEANS ARLES ECOM AZUL CLARO');
insert into tb_produto (co_produto, co_categoria, vl_preco, nu_quantidade, ds_produto) values (15, 99, 145, 45, 'CALÇA CONFORT LISA PRETO');
insert into tb_produto (co_produto, co_categoria, vl_preco, nu_quantidade, ds_produto) values (16, 99, 145, 45, 'CALÇA CHINO VERDE ESCURO');
insert into tb_produto (co_produto, co_categoria, vl_preco, nu_quantidade, ds_produto) values (17, 99, 145, 45, 'CALÇA JEANS MOLETOM CONFORT MÉDIA JEANS');
insert into tb_produto (co_produto, co_categoria, vl_preco, nu_quantidade, ds_produto) values (18, 99, 118, 27, 'CAMISA MANGA CURTA ESTAMPADA DOTS UNICA');
insert into tb_produto (co_produto, co_categoria, vl_preco, nu_quantidade, ds_produto) values (19, 99, 118, 27, 'CAMISA MC EST POA PRINTED UNICA');
insert into tb_produto (co_produto, co_categoria, vl_preco, nu_quantidade, ds_produto) values (20, 99, 118, 27, 'CAMISA MC EST TAHITI PB UNICA');
insert into tb_produto (co_produto, co_categoria, vl_preco, nu_quantidade, ds_produto) values (21, 99, 118, 27, 'CAMISA MANGA CURTA ESTAMPA ART FLOWER PRETO');	

insert into tb_pedido values (1,'03/08/2020',1,2);
insert into tb_pedido values (2,'03/08/2020',1,2);
insert into tb_pedido values (3,'03/08/2020',1,2);
insert into tb_pedido values (4,'03/08/2020',2,2);
insert into tb_pedido values (5,'03/08/2020',2,2);
insert into tb_pedido values (6,'03/08/2020',2,2);
insert into tb_pedido values (7,'03/08/2020',2,2);
insert into tb_pedido values (8,'03/08/2020',3,2);
insert into tb_pedido values (9,'03/08/2020',3,2);
insert into tb_pedido values (10,'03/08/2020',3,2);
insert into tb_pedido values (11,'03/08/2020',3,2);
insert into tb_pedido values (12,'03/08/2020',4,2);
insert into tb_pedido values (13,'03/08/2020',4,2);
insert into tb_pedido values (14,'03/08/2020',4,2);
insert into tb_pedido values (15,'03/08/2020',5,2);
insert into tb_pedido values (16,'03/08/2020',5,2);
insert into tb_pedido values (17,'03/08/2020',5,2);
insert into tb_pedido values (18,'03/08/2020',5,2);
insert into tb_pedido values (19,'03/08/2020',6,2);
insert into tb_pedido values (20,'03/08/2020',6,2);
insert into tb_pedido values (21,'03/08/2020',7,2);
insert into tb_pedido values (22,'03/08/2020',7,2);
insert into tb_pedido values (23,'03/08/2020',7,2);
insert into tb_pedido values (24,'03/08/2020',8,2);
insert into tb_pedido values (25,'03/08/2020',8,2);
insert into tb_pedido values (26,'03/08/2020',8,2);
insert into tb_pedido values (27,'03/08/2020',9,2);
insert into tb_pedido values (28,'03/08/2020',10,2);
insert into tb_pedido values (29,'03/08/2020',10,2);
insert into tb_pedido values (30,'03/08/2020',10,2);
insert into tb_pedido values (31,'03/08/2020',11,2);
insert into tb_pedido values (32,'03/08/2020',11,2);
insert into tb_pedido values (33,'03/08/2020',11,2);
insert into tb_pedido values (34,'03/08/2020',12,2);
insert into tb_pedido values (35,'03/08/2020',12,2);
insert into tb_pedido values (36,'03/08/2020',13,2);
insert into tb_pedido values (37,'03/08/2020',14,2);
insert into tb_pedido values (38,'03/08/2020',15,2);
insert into tb_pedido values (39,'03/08/2020',16,2);
insert into tb_pedido values (40,'03/08/2020',17,2);
insert into tb_pedido values (41,'03/08/2020',17,2);
insert into tb_pedido values (42,'03/08/2020',17,2);
insert into tb_pedido values (43,'03/08/2020',20,2);
insert into tb_pedido values (44,'03/08/2020',20,2);
insert into tb_pedido values (45,'03/08/2020',20,2);
insert into tb_pedido values (46,'03/08/2020',20,2);
insert into tb_pedido values (47,'03/08/2020',20,2);
insert into tb_pedido values (48,'03/08/2020',20,2);
insert into tb_pedido values (49,'03/08/2020',20,2);
insert into tb_pedido values (50,'03/08/2020',20,2);
insert into tb_pedido values (51,'03/08/2020',20,2);
insert into tb_pedido values (52,'04/09/2020',20,2);
insert into tb_pedido values (53,'04/09/2020',20,2);
insert into tb_pedido values (54,'04/09/2020',20,2);
insert into tb_pedido values (55,'04/09/2020',20,2);
insert into tb_pedido values (56,'04/09/2020',20,2);
insert into tb_pedido values (57,'04/09/2020',20,2);
insert into tb_pedido values (58,'04/09/2020',20,2);
insert into tb_pedido values (59,'04/09/2020',20,2);
insert into tb_pedido values (60,'04/09/2020',20,2);
insert into tb_pedido values (61,'04/09/2020',20,2);
insert into tb_pedido values (62,'04/09/2020',20,2);
insert into tb_pedido values (63,'04/09/2020',20,2);
insert into tb_pedido values (64,'04/09/2020',20,2);
insert into tb_pedido values (65,'04/09/2020',20,2);
insert into tb_pedido values (66,'04/09/2020',20,2);
insert into tb_pedido values (67,'04/09/2020',20,2);
insert into tb_pedido values (68,'04/09/2020',20,2);
insert into tb_pedido values (69,'04/09/2020',20,2);
insert into tb_pedido values (70,'04/09/2020',20,2);
insert into tb_pedido values (71,'04/09/2020',20,2);
insert into tb_pedido values (72,'04/09/2020',20,2);
insert into tb_pedido values (73,'04/09/2020',20,2);
insert into tb_pedido values (74,'04/09/2020',20,2);
insert into tb_pedido values (75,'04/09/2020',20,2);
insert into tb_pedido values (76,'04/09/2020',20,2);
insert into tb_pedido values (77,'04/09/2020',20,2);
insert into tb_pedido values (78,'04/09/2020',20,2);
insert into tb_pedido values (79,'04/09/2020',20,2);
insert into tb_pedido values (80,'04/09/2020',20,2);
insert into tb_pedido values (81,'04/09/2020',20,2);
insert into tb_pedido values (82,'04/09/2020',20,2);
insert into tb_pedido values (83,'04/09/2020',20,2);
insert into tb_pedido values (84,'04/09/2020',20,2);
insert into tb_pedido values (85,'04/09/2020',20,2);
insert into tb_pedido values (86,'04/09/2020',20,2);
insert into tb_pedido values (87,'10/12/2020',20,2);
insert into tb_pedido values (88,'10/12/2020',20,2);
insert into tb_pedido values (89,'10/12/2020',20,2);
insert into tb_pedido values (90,'10/12/2020',20,2);
insert into tb_pedido values (91,'10/12/2020',20,2);
insert into tb_pedido values (92,'10/12/2020',20,2);
insert into tb_pedido values (93,'10/12/2020',20,2);
insert into tb_pedido values (94,'10/12/2020',20,2);
insert into tb_pedido values (95,'10/12/2020',20,2);
insert into tb_pedido values (96,'10/12/2020',20,2);
insert into tb_pedido values (97,'10/12/2020',20,2);
insert into tb_pedido values (98,'10/12/2020',20,2);
insert into tb_pedido values (99,'10/12/2020',20,2);
insert into tb_pedido values (100,'10/12/2020',20,2);
insert into tb_pedido values (101,'10/12/2020',20,2);
insert into tb_pedido values (102,'10/12/2020',20,2);
insert into tb_pedido values (103,'10/12/2020',20,2);
insert into tb_pedido values (104,'10/12/2020',20,2);
insert into tb_pedido values (105,'10/12/2020',20,2);
insert into tb_pedido values (106,'10/12/2020',20,2);
insert into tb_pedido values (107,'10/12/2020',20,2);
insert into tb_pedido values (108,'10/12/2020',20,2);
insert into tb_pedido values (109,'10/12/2020',20,2);
insert into tb_pedido values (110,'10/12/2020',20,2);
insert into tb_pedido values (111,'10/12/2020',20,2);
insert into tb_pedido values (112,'10/12/2020',20,2);
insert into tb_pedido values (113,'10/12/2020',20,2);
insert into tb_pedido values (114,'10/12/2020',20,2);
insert into tb_pedido values (115,'10/12/2020',20,2);
insert into tb_pedido values (116,'10/12/2020',20,2);
insert into tb_pedido values (117,'10/12/2020',20,2);
insert into tb_pedido values (118,'10/12/2020',20,2);
insert into tb_pedido values (119,'10/12/2020',20,2);
insert into tb_pedido values (120,'10/12/2020',20,2);
insert into tb_pedido values (121,'10/12/2020',20,2);
insert into tb_pedido values (122,'10/12/2020',20,2);
insert into tb_pedido values (123,'10/12/2020',20,2);
insert into tb_pedido values (124,'10/12/2020',20,2);
insert into tb_pedido values (125,'10/12/2020',20,2);
insert into tb_pedido values (126,'10/12/2020',20,2);
insert into tb_pedido values (127,'10/12/2020',20,2);
insert into tb_pedido values (128,'10/12/2020',20,2);
insert into tb_pedido values (129,'10/12/2020',20,2);
insert into tb_pedido values (130,'10/12/2020',20,2);
insert into tb_pedido values (131,'10/12/2020',20,2);
insert into tb_pedido values (132,'10/12/2020',20,2);


insert into tb_pedido_item values (1,'1',1,100,1);
insert into tb_pedido_item values (2,'2',2,100,1);
insert into tb_pedido_item values (3,'3',3,100,1);
insert into tb_pedido_item values (4,'4',4,100,1);
insert into tb_pedido_item values (5,'5',5,100,1);
insert into tb_pedido_item values (6,'6',6,100,1);
insert into tb_pedido_item values (7,'7',7,100,1);
insert into tb_pedido_item values (8,'8',8,100,1);
insert into tb_pedido_item values (9,'9',9,100,1);
insert into tb_pedido_item values (10,'10',10,100,1);
insert into tb_pedido_item values (11,'11',11,100,1);
insert into tb_pedido_item values (12,'12',12,100,1);
insert into tb_pedido_item values (13,'13',13,100,1);
insert into tb_pedido_item values (14,'14',14,100,1);
insert into tb_pedido_item values (15,'15',15,100,1);
insert into tb_pedido_item values (16,'16',16,100,1);
insert into tb_pedido_item values (17,'17',17,100,1);
insert into tb_pedido_item values (18,'18',18,100,1);
insert into tb_pedido_item values (19,'19',19,100,1);
insert into tb_pedido_item values (20,'19',19,100,1);
insert into tb_pedido_item values (21,'19',19,100,1);
insert into tb_pedido_item values (22,'19',19,100,1);
insert into tb_pedido_item values (23,'19',19,100,1);
insert into tb_pedido_item values (24,'19',19,100,1);
insert into tb_pedido_item values (25,'19',19,100,1);
insert into tb_pedido_item values (26,'19',19,100,1);
insert into tb_pedido_item values (27,'19',19,100,1);
insert into tb_pedido_item values (28,'19',19,100,1);
insert into tb_pedido_item values (29,'19',19,100,1);
insert into tb_pedido_item values (30,'19',19,100,1);
insert into tb_pedido_item values (31,'19',19,100,1);
insert into tb_pedido_item values (32,'19',19,100,1);
insert into tb_pedido_item values (33,'19',19,100,1);
insert into tb_pedido_item values (34,'19',19,100,1);
insert into tb_pedido_item values (35,'19',19,100,1);
insert into tb_pedido_item values (36,'19',19,100,1);
insert into tb_pedido_item values (37,'19',19,100,1);
insert into tb_pedido_item values (38,'19',19,100,1);
insert into tb_pedido_item values (39,'19',19,100,1);
insert into tb_pedido_item values (40,'19',19,100,1);
insert into tb_pedido_item values (41,'19',19,100,1);
insert into tb_pedido_item values (42,'19',19,100,1);
insert into tb_pedido_item values (43,'19',19,100,1);
insert into tb_pedido_item values (44,'19',19,100,1);
insert into tb_pedido_item values (45,'19',19,100,1);
insert into tb_pedido_item values (46,'19',19,100,1);
insert into tb_pedido_item values (47,'19',19,100,1);
insert into tb_pedido_item values (48,'19',19,100,1);
insert into tb_pedido_item values (49,'19',19,100,1);
insert into tb_pedido_item values (50,'19',19,100,1);
insert into tb_pedido_item values (51,'19',19,100,1);
insert into tb_pedido_item values (52,'19',19,100,1);
insert into tb_pedido_item values (53,'19',19,100,1);
insert into tb_pedido_item values (55,'19',19,100,1);
insert into tb_pedido_item values (56,'19',19,100,1);
insert into tb_pedido_item values (57,'19',19,100,1);
insert into tb_pedido_item values (58,'19',19,100,1);
insert into tb_pedido_item values (59,'19',19,100,1);
insert into tb_pedido_item values (60,'19',19,100,1);
insert into tb_pedido_item values (61,'19',19,100,1);
insert into tb_pedido_item values (62,'19',19,100,1);
insert into tb_pedido_item values (63,'19',19,100,1);
insert into tb_pedido_item values (64,'19',19,100,1);
insert into tb_pedido_item values (65,'19',19,100,1);
insert into tb_pedido_item values (66,'19',19,100,1);
insert into tb_pedido_item values (67,'19',19,100,1);
insert into tb_pedido_item values (68,'19',19,100,1);
insert into tb_pedido_item values (69,'19',19,100,1);
insert into tb_pedido_item values (70,'19',19,100,1);
insert into tb_pedido_item values (71,'19',19,100,1);
insert into tb_pedido_item values (72,'19',19,100,1);
insert into tb_pedido_item values (73,'19',19,100,1);
insert into tb_pedido_item values (74,'19',19,100,1);
insert into tb_pedido_item values (75,'19',19,100,1);
insert into tb_pedido_item values (76,'19',19,100,1);
insert into tb_pedido_item values (77,'19',19,100,1);
insert into tb_pedido_item values (79,'19',19,100,1);
insert into tb_pedido_item values (80,'19',19,100,1);
insert into tb_pedido_item values (81,'19',19,100,1);
insert into tb_pedido_item values (82,'19',19,100,1);
insert into tb_pedido_item values (83,'19',19,100,1);
insert into tb_pedido_item values (84,'19',19,100,1);
insert into tb_pedido_item values (85,'19',19,100,1);
insert into tb_pedido_item values (86,'19',19,100,1);
insert into tb_pedido_item values (87,'19',19,100,1);
insert into tb_pedido_item values (88,'19',19,100,1);
insert into tb_pedido_item values (89,'19',19,100,1);
insert into tb_pedido_item values (90,'19',19,100,1);
insert into tb_pedido_item values (91,'19',19,100,1);
insert into tb_pedido_item values (92,'19',19,100,1);
insert into tb_pedido_item values (93,'19',19,100,1);
insert into tb_pedido_item values (94,'19',19,100,1);
insert into tb_pedido_item values (95,'19',19,100,1);
insert into tb_pedido_item values (96,'19',19,100,1);
insert into tb_pedido_item values (97,'19',19,100,1);
insert into tb_pedido_item values (98,'19',19,100,1);
insert into tb_pedido_item values (99,'19',19,100,1);

--corrigindo o SERIAL

SELECT setval(pg_get_serial_sequence('tb_categoria', 'co_categoria'), coalesce(max(co_categoria), 0)+1 , false) FROM tb_categoria;
SELECT setval(pg_get_serial_sequence('tb_cliente', 'co_cliente'), coalesce(max(co_cliente), 0)+1 , false) FROM tb_cliente;
SELECT setval(pg_get_serial_sequence('tb_produto', 'co_produto'), coalesce(max(co_produto), 0)+1 , false) FROM tb_produto;
SELECT setval(pg_get_serial_sequence('tb_status_pedido', 'co_status'), coalesce(max(co_status), 0)+1 , false) FROM tb_status_pedido;
SELECT setval(pg_get_serial_sequence('tb_pedido', 'co_pedido'), coalesce(max(co_pedido), 0)+1 , false) FROM tb_pedido;
SELECT setval(pg_get_serial_sequence('tb_pedido_item', 'co_pedido_item'), coalesce(max(co_pedido_item), 0)+1 , false) FROM tb_pedido_item;






